//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharitAble_current.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGOResponse
    {
        public int ResponseID { get; set; }
        public int NGO_ID { get; set; }
        public int DonationID { get; set; }
        public string Address { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> PostedDateTime { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string isActive { get; set; }
    }
}
