//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharitAble_current.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MaterialMaster
    {
        public int MaterialID { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<int> MaterialTypeID { get; set; }
        public Nullable<int> MaterialGroupID { get; set; }
        public string MaterialName { get; set; }
        public string MaterialDescription { get; set; }
    
        public virtual tbl_Admin tbl_Admin { get; set; }
        public virtual tbl_MaterialGroup tbl_MaterialGroup { get; set; }
        public virtual tbl_MaterialType tbl_MaterialType { get; set; }
    }
}
