//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharitAble_current.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Orders()
        {
            this.tbl_Invoices = new HashSet<tbl_Invoices>();
        }
    
        public int OrderID { get; set; }
        public Nullable<int> NGO_ID { get; set; }
        public Nullable<int> CaseID { get; set; }
        public Nullable<int> ReplyID { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public Nullable<System.DateTime> OrderDateTime { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> DonorID { get; set; }
        public Nullable<int> ResponseID { get; set; }
        public Nullable<int> DonationID { get; set; }
    
        public virtual tbl_Cases tbl_Cases { get; set; }
        public virtual tbl_DonorReplies tbl_DonorReplies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Invoices> tbl_Invoices { get; set; }
        public virtual tbl_PaymentInfo tbl_PaymentInfo { get; set; }
        public virtual NGOResponse NGOResponse { get; set; }
        public virtual tbl_DonorMaster tbl_DonorMaster { get; set; }
        public virtual tbl_Donations tbl_Donations { get; set; }
    }
}
