//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharitAble_current.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Invoices
    {
        public int InvoiceID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> DonorID { get; set; }
        public Nullable<int> NGO_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual tbl_DonorMaster tbl_DonorMaster { get; set; }
        public virtual tbl_NGOMaster tbl_NGOMaster { get; set; }
        public virtual tbl_Orders tbl_Orders { get; set; }
    }
}
