//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharitAble_current.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Donations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Donations()
        {
            this.NGOResponses = new HashSet<NGOResponse>();
            this.tbl_Orders = new HashSet<tbl_Orders>();
        }
    
        public int DonationID { get; set; }
        public Nullable<int> CaseID { get; set; }
        public Nullable<int> DonorID { get; set; }
        public string DonationTitle { get; set; }
        public Nullable<int> Condition { get; set; }
        public Nullable<short> Quantity { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<short> QuantityPerUnit { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> PostedDateTime { get; set; }
        public string isActive { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
    
        public virtual tbl_Cases tbl_Cases { get; set; }
        public virtual tbl_DonationCondition tbl_DonationCondition { get; set; }
        public virtual tbl_DonorMaster tbl_DonorMaster { get; set; }
        public virtual tbl_Status tbl_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGOResponse> NGOResponses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Orders> tbl_Orders { get; set; }
    }
}
