//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharitAble_current.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Donations
    {
        public int DonationID { get; set; }
        public Nullable<int> DonorID { get; set; }
        public string DonationTitle { get; set; }
        public Nullable<short> Quantity { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<byte> QuantityPerUnit { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Description { get; set; }
        public Nullable<long> LocationCoordinates { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual tbl_DonorMaster tbl_DonorMaster { get; set; }
    }
}
